# Orchestra Device Configuration
# Devices are hardware platforms, NOT projects
# Projects (like "puppy") are built on top of devices

devices:
  ev3:
    platform: ev3
    host: 192.168.68.111
    user: robot
    password: maker
    sudo_password: maker

  spike:
    platform: spike_prime
    name: Avatar Karo
    address: E1BDF5C6-C666-4E77-A7E8-458FC0A9F809
