# Puppy Robot Actions
# Translated to generic daemon commands by ActionAdapter
#
# Motor ports: A=right leg, C=head, D=left leg
# Sensors: S1=touch, S4=color

actions:
  sitdown:
    description: "Sit down (fold legs to resting position)"
    steps:
      - [eyes happy, 0]
      - [target2 D A 0 150, 1500]

  standup:
    description: "Stand up (push legs to lift body)"
    steps:
      - [eyes neutral, 0]
      - [target2 D A -55 100, 1800]

  calibrate:
    description: "Calibrate - set current position as standing (0 degrees)"
    steps:
      - [reset, 0]
      - [eyes neutral, 0]
      - [beep 440 100, 100]
      - [beep 880 100, 0]

  bark:
    description: "Bark (woof woof)"
    steps:
      - [eyes surprised, 0]
      - [sound dog_bark, 0]

  stretch:
    description: "Stretch legs"
    steps:
      - [eyes sleepy, 0]
      - [motor D 80 500, 0]
      - [motor A 80 500, 300]
      - [motor D 60 600, 0]
      - [motor A 60 600, 300]
      - [motor D 80 800, 0]
      - [motor A 80 800, 300]
      - [motor D -80 800, 0]
      - [motor A -80 800, 300]
      - [eyes neutral, 0]

  hop:
    description: "Jump"
    steps:
      - [eyes surprised, 0]
      - [motor D 350 300, 0]
      - [motor A 350 300, 350]
      - [motor D -180 350, 0]
      - [motor A -180 350, 400]

  head_up:
    description: "Raise head"
    steps:
      - [eyes neutral, 0]
      - [motor C 50 600, 0]

  head_down:
    description: "Lower head"
    steps:
      - [eyes sleepy, 0]
      - [motor C -50 600, 0]

  happy:
    description: "Happy expression with dance"
    steps:
      - [eyes happy, 0]
      - [sound dog_bark, 0]
      - [motor D 120, 0]
      - [motor A 120, 300]
      - [stop, 200]
      - [motor D -60, 0]
      - [motor A -60, 300]
      - [stop, 0]
      - [sound dog_bark, 0]

  angry:
    description: "Angry expression with growl"
    steps:
      - [eyes angry, 0]
      - [sound dog_growl, 0]
      - [motor D 80 500, 0]
      - [motor A 80 500, 300]
      - [motor D 60 600, 0]
      - [motor A 60 600, 0]
      - [sound dog_bark, 0]

  sleep:
    description: "Go to sleep"
    steps:
      - [eyes sleepy, 0]
      - [target2 D A 0 100, 1500]
      - [display Zzz..., 0]

  wakeup:
    description: "Wake up"
    steps:
      - [eyes surprised, 0]
      - [beep 880 200, 0]
      - [target2 D A -90 150, 1500]
      - [eyes neutral, 0]

  playful:
    description: "Playful mood"
    steps:
      - [eyes happy, 0]
      - [motor D 100 300, 0]
      - [motor A 100 300, 150]
      - [motor D -100 300, 0]
      - [motor A -100 300, 150]
      - [motor D 100 300, 0]
      - [motor A 100 300, 150]
      - [sound dog_bark, 0]


